### ISSUE TITLE
Unable To SlipStream Any Driver Unless Its The SATA One

### ISSUE THREAD

**Issue by halal-beef** [halal-beef/HP-Notebook-15-XP-Drivers#1]
Presumably it **DOES** slipstream but it will refuse to install through NLite because of Windows File Protection (WFP) expecting a certificate

It also seems like nlite disabling it isn't enough

Potential Solution:

Make my own certs and sign the drivers

**Comment by SmallPP420** [comment]
i wont make my own certs ill use the win-raid certs

**Comment by SmallPP420** [comment]
*sigh* this is gonna be harder than I thought
